# Generated by Django 3.0.4 on 2020-05-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_poststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststatus',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published')], default=('DRAFT', 'draft'), max_length=10),
        ),
    ]
