# Generated by Django 3.0.4 on 2020-05-08 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200508_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststatus',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
